server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finledger
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true
  flyway:
    enabled: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    trade-created: trade.created.queue
  exchange:
    trade-exchange: trade.created.exchange

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  pattern:
    level: "%d{yyyy-MM-dd HH:mm:ss} [%X{correlationId} %-5level %logger{36} - %msg%n"