version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: finledger-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finledger
    ports:
      - "5432:5432"
    volumes:
      - finledger_volume:/var/lib/postgresql/data
    networks:
      - monitoring

  rabbitmq:
    image: rabbitmq:3-management
    container_name: finledger-rabbit
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
      - "15692:15692"   # Prometheus metrics
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      sh -c "rabbitmq-plugins enable --offline rabbitmq_prometheus &&
             rabbitmq-server"
    networks:
      - monitoring
      
  otel-collector:
    image: otel/opentelemetry-collector:0.104.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    networks:
      - monitoring

  tempo:
    image: grafana/tempo:2.5.0
    command: ["-config.file=/etc/tempo.yaml"]
    ports:
      - "3200:3200"
      - "9095:9095"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml:ro
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:v2.54.1
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "4000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - prometheus
      - tempo
    networks:
      - monitoring

volumes:
  finledger_volume:

networks:
  monitoring:
    driver: bridge
